apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: argoapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
